### ISSUE TITLE
content not being blocked

### ISSUE THREAD

**Issue by glitchdigger** [CartographerLabs/Canary#1]
Thus far I've not been able to achieve an accurate test of the intended functionality. I setup an Oauth2 flow and included the clientid in the manifest. I was able to receive the customized Grant window, but from then onward no traffic relating to gophers (I changed the prompt to filter gophers) were filtered. So it wasn't filtering content about extremism, gophers, or extremist gophers.

**Comment by user1342** [comment]
Hi Alec,
Thanks for your interest in Canary and for taking the time to get it setup! Let's work out what's causing the problem you're having. 

There is a known issue with the Chrome extension's Google OAuth Cloud implementation, however, that shouldn't be effecting you as it sounds like you've connected the project to your own Google Cloud instance. 

Let's start with checking the below to make sure everything is working as it should. 

- When you setup your Google Cloud project, did you add the necessary Vertex API scopes, alongside adding your email as a test user? 
- After selecting `grant` on the Canary permission popup were you then taken (or taken after refreshing the page) to the Google OAuth prompt asking you to sign in to your Google account and to provide Canary access? (See the video on the Readme for what this should look like). 
- Did the test file trigger as expected? (See Readme for how to test this). 

If you've gone through the above and everything is as expected, the next step will be to enable the `debug_mode` variable in both `content.js`and `background.js`, then on your visited webpage and the background service (via the extension page) open the [Google developer console ](https://developer.chrome.com/docs/devtools/open). Once there you should see logs for the created prompt, response from Gemini, and if the content was flagged. 

Once there let me know what those logs look like and we'll take it from there!

Cheers,
James

**Comment by user1342** [comment]
As it's been a month since this was created and there has been no response since I'm marking this as closed. Please attempt the steps above for a fix if it's still a concern. 

Cheers, 
James
